// ─── snake_case (DB) ⇄ camelCase (app) ────────────────────────────────────────

export const userFromRow = (r) => ({
  id: r.id,
  name: r.name,
  email: r.email,
  role: r.role,
  region: r.region,
  phone: r.phone,
  active: r.active,
  joinedAt: r.joined_at,
  passwordHash: r.password_hash,
})

export const userToRow = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  role: u.role,
  region: u.region ?? null,
  phone: u.phone,
  active: u.active,
  joined_at: u.joinedAt,
  password_hash: u.passwordHash,
})

export const complaintFromRow = (r) => ({
  id: r.id,
  complaintNo: r.complaint_no || '',
  customer: r.customer,
  contact: r.contact,
  email: r.email || '',
  branch: r.branch || '',
  branchCode: r.branch_code || '',
  zone: r.zone || '',
  region: r.region,
  city: r.city,
  district: r.district || '',
  category: r.category,
  type: r.type,
  priority: r.priority,
  status: r.status,
  assignedTo: r.assigned_to,
  loggedBy: r.logged_by,
  loggedAt: r.logged_at,
  description: r.description || '',
  fsr: r.fsr,
  fsrNotes: r.fsr_notes || '',
  attachments: r.attachments || [],
  resolutionPath: r.resolution_path || '',
  unitId: r.unit_id || '',
  productSerial: r.product_serial || '',
  warrantyExpiry: r.warranty_expiry || '',
  paymentStatus: r.payment_status,
  slaHours: r.sla_hours,
  workshopAssigned: r.workshop_assigned,
  backupUnitInstalled: r.backup_unit_installed,
  repairLog: r.repair_log || [],
  timeline: r.timeline || [],
})

export const complaintToRow = (c) => ({
  id: c.id,
  complaint_no: c.complaintNo || '',
  customer: c.customer,
  contact: c.contact,
  email: c.email || '',
  branch: c.branch || '',
  branch_code: c.branchCode || '',
  zone: c.zone || '',
  region: c.region,
  city: c.city,
  district: c.district || '',
  category: c.category,
  type: c.type,
  priority: c.priority,
  status: c.status,
  assigned_to: c.assignedTo ?? null,
  logged_by: c.loggedBy,
  logged_at: c.loggedAt,
  description: c.description || '',
  fsr: c.fsr ?? null,
  fsr_notes: c.fsrNotes || '',
  attachments: c.attachments || [],
  resolution_path: c.resolutionPath || '',
  unit_id: c.unitId || '',
  product_serial: c.productSerial || '',
  warranty_expiry: c.warrantyExpiry || '',
  payment_status: c.paymentStatus,
  sla_hours: c.slaHours,
  workshop_assigned: c.workshopAssigned ?? null,
  backup_unit_installed: c.backupUnitInstalled,
  repair_log: c.repairLog || [],
  timeline: c.timeline || [],
  updated_at: new Date().toISOString(),
})
